In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
pd.__version__

'2.2.2'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-10-01 21:26:10--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv.3’

laptops.csv.3       100%[===================>] 291.58K  --.-KB/s    in 0.01s   

2024-10-01 21:26:10 (24.4 MB/s) - ‘laptops.csv.3’ saved [298573/298573]



In [4]:
df = pd.read_csv("laptops.csv")

In [5]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [7]:
print("The number of records in the dataset is", len(df))

The number of records in the dataset is 2160


In [8]:
# Counting distinct values
print("The number of laptop brands present in the dataset is", df['Brand'].nunique())

The number of laptop brands present in the dataset is 27


In [9]:
null_columns = df.isna().sum()
print(null_columns)

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64


In [10]:
columns_that_have_null = (null_columns > 0).sum()
print(f"Number of columns with null values are {columns_that_have_null}")

Number of columns with null values are 3


In [11]:
df.describe().T

count         mean         std     min       25%       50%  \
RAM          2160.0    15.413889    9.867815    4.00    8.0000    16.000   
Storage      2160.0   596.294444  361.220506    0.00  256.0000   512.000   
Screen       2156.0    15.168112    1.203329   10.10   14.0000    15.600   
Final Price  2160.0  1312.638509  911.475417  201.05  661.0825  1031.945   

                 75%      max  
RAM            16.00   128.00  
Storage      1000.00  4000.00  
Screen         15.60    18.00  
Final Price  1708.97  7150.47

In [12]:
df.groupby(['Brand'])['Final Price'].max()

Brand
Acer                3691.00
Alurin               869.00
Apple               3849.00
Asus                5758.14
Deep Gaming         1639.01
Dell                3936.00
Denver               329.95
Dynabook Toshiba    1805.01
Gigabyte            3799.00
HP                  5368.77
Innjoo               431.38
Jetwing              469.27
LG                  2399.00
Lenovo              5018.14
MSI                 7150.47
Medion              3799.00
Microsoft           3747.91
Millenium           2312.71
PcCom               1949.90
Primux               599.41
Prixton              329.95
Razer               4999.01
Realme               999.00
Samsung             3699.01
Thomson              436.56
Toshiba              799.00
Vant                1217.01
Name: Final Price, dtype: float64

In [13]:
dell_laptop = df[df['Brand'] =='Dell']

dell_laptop

Laptop       Status Brand  \
161   Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...          New  Dell   
271   Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...          New  Dell   
281   Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...          New  Dell   
319   Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...          New  Dell   
328   Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...          New  Dell   
...                                                 ...          ...   ...   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
1844  Dell Vostro 5301 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1845  Dell Vostro 5502 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1846  Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512G...  Refurbished  Dell   
1847  Dell XPS 7390 Intel Core i7-10510U/16GB/512GB ...  Refurbished  Dell   

         Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
161     Vostro  Intel Core i3    8      256          SSD  NaN    15.6    No   
271     Vostro  Intel Core i5    8      256          SSD  NaN    15.6    No   
281     Vostro  Intel Core i7   16      512          SSD  NaN    15.6    No   
319   Latitude  Intel Core i5    8      256          SSD  NaN    15.6    No   
328     Vostro  Intel Core i5   16      512          SSD  NaN    15.6    No   
...        ...            ...  ...      ...          ...  ...     ...   ...   
1843    Vostro  Intel Core i5    8      256          SSD  NaN    13.3    No   
1844    Vostro  Intel Core i5    8      512          SSD  NaN    13.3    No   
1845    Vostro  Intel Core i5    8      512          SSD  NaN    15.6    No   
1846       XPS  Intel Core i5    8      512          SSD  NaN    13.4    No   
1847       XPS  Intel Core i7   16      512          SSD  NaN    13.3    No   

      Final Price  
161        599.00  
271        690.15  
281        889.00  
319        789.00  
328        869.00  
...           ...  
1843       420.74  
1844       511.59  
1845       549.93  
1846       699.00  
1847      1086.88  

[84 rows x 12 columns]

In [14]:
print('The maximum final price of dell notbooks in the dataset is',dell_laptop['Final Price'].max())

The maximum final price of dell notbooks in the dataset is 3936.0


In [15]:
median_value_of_screen = df['Screen'].median()
median_value_of_screen

15.6

In [16]:
most_frequent_value_of_screen = df['Screen'].mode()[0]
most_frequent_value_of_screen

15.6

In [17]:
df['Screen'].fillna(most_frequent_value_of_screen)
print(df['Screen'])

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64


In [18]:
df['Screen'].median()

15.6

No, the median value of screen has did not change

In [19]:
# Selecting only the innjoo laptops from the dataset
innjoo_laptops = df[df['Brand'] == 'Innjoo']

In [20]:
#selecting only columns RAM, Storage and Screen
only_columns = innjoo_laptops[['RAM', 'Storage', 'Screen']]
only_columns

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [21]:
#Converting the values to numpy
X = only_columns.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [22]:
#Transposing the matrix X
Transpose_X = X.T
Transpose_X

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [23]:
#Computing the matrix-matrix multiplication between the transpose of X and X
XTX = Transpose_X.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [24]:
# Creating an inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [25]:
# Creating a numpy array 
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [26]:
#Multiplying the inverse of XTX with the transpose of X
result = np.matmul(XTX_inv, Transpose_X)
result

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [27]:
#Multiplying the result with y
w = np.dot(result, y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [28]:
print(f"The sum of the array is: {np.sum(w)}")

The sum of the array is: 91.29988062995496
